export const projects = [
  {
    title: "Corkowl",
    tags: ["Vue.js", "SASS", "HTML", "CSS", "Javascript"],
    description: "Landing Page for Wine E-commerce SaaS product",
    code: "",
    website: "http://www.corkowl.xyz/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1659563896/divz.xyz/Screenshot_2022-08-04_032736_n0bbdo.png",
  },
  ,
  {
    title: "Grammarly Premium Clone ",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript"],
    description: "Frontend clone of Grammarly Premium Landing Page",
    code: "https://github.com/divzhere/GrammarlyLandingPage",
    website: "http://grammarly-landing-page.vercel.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629840066/divz.xyz/screenshot-grammarly-landing-page.vercel.app-2021.08.25-02_48_29_gbyqun.png",
  },
  {
    title: "Amazon Clone",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript", "Firebase", "Stripe"],
    description:
      "Clone of Amazon with Login/Signup, Checkout and Payment features",
    code: "https://github.com/divzhere/AmazonClone",
    website: "https://amazon-clone-chi-five.vercel.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629840053/divz.xyz/screenshot-amazon-clone-chi-five.vercel.app-2021.08.25-02_48_41_p7px6q.png",
  },
  {
    title: "Better Maps",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript"],
    description:
      "MVP for a Web app for creating Maps using Mapbox and Maptiler APIs",
    code: "https://github.com/divzhere/BetterMaps",
    website: "https://hungry-hypatia-83f595.netlify.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629465653/divz.xyz/bettermaps.293b3880_txflwz.png",
  },
  {
    title: "Netflix Home Page Clone",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript"],
    description:
      "Used Movies Database API for making a clone of Netflix Home page UI",
    code: "https://github.com/divzhere/netflix-clone",
    website: "https://t8x43.csb.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629465659/divz.xyz/netflix.8305b132_wg159a.png",
  },
  {
    title: "react-multiselect-dropdown",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript"],
    description: "Reusable Multiselect Dropdown Component",
    code: "https://github.com/divzhere/react-multiselect-dropdown",
    website: "https://csb-duysh.netlify.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629465663/divz.xyz/multiselect.870ec34e_z0peyn.png",
  },
  {
    title: "divz.xyz",
    tags: [
      "React",
      "SASS",
      "HTML",
      "CSS",
      "Javascript",
      "Google Analytics",
      "Cloudinary",
    ],
    description: "My personal website",
    code: "https://github.com/divzhere/divyum",
    website: "http://divz.xyz/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629465667/divz.xyz/divz.ff33c1ef_ad4iyu.png",
  },
  {
    title: "Fix n Flip Loans",
    tags: ["React", "SASS", "HTML", "CSS", "Javascript"],
    description: "Landing page for a Loan lending Company.",
    code: "",
    website: "https://loving-goldstine-af3e96.netlify.app/",
    img: "https://res.cloudinary.com/dbrdml9bf/image/upload/v1629465673/divz.xyz/loan.2c821bba_l14od9.png",
  },
];
